# Generated by Django 5.0.6 on 2024-08-14 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('surname', models.CharField(default='', max_length=100)),
                ('mobile_number', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(default='unknown', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('bio', models.TextField(default='This is a default bio.')),
                ('work', models.CharField(default='Current work information.', max_length=255)),
                ('education', models.CharField(default='Education details here.', max_length=255)),
                ('location', models.CharField(default='Location information.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user_data')),
            ],
        ),
    ]
