# Generated by Django 5.0.6 on 2024-09-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_data_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='profile_pictures',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
