# Generated by Django 5.0.6 on 2024-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_data_profile_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='profile_pictures',
        ),
        migrations.AlterField(
            model_name='user_data',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
