# Generated by Django 5.1.7 on 2025-12-29 05:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_post_image_alter_post_video_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="post_image"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="post_video"
            ),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="cover_photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="cover_photo"
            ),
        ),
        migrations.AlterField(
            model_name="user_data",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile_picture"
            ),
        ),
    ]
